version: '2'

services:
    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - 80:3306
        environment:
            - MYSQL_DATABASE=enssapp
            - MYSQL_ROOT_PASSWORD=12rR8tY45
            - MYSQL_USER=user
            - MYSQL_PASSWORD=12rR8tY45